### ISSUE TITLE
PetriNet.__pnmlload__()

### ISSUE THREAD

**Issue by pksec** [fpom/snakes#16]
##  What I want to achieve
I want to dump pnml from one PetriNet and send it to another python program, load the pnml in the other program.

This might not be an issue, but more like an request or how to solve the problem question.
### Here is my sample code and what I want to achieve.
```
from snakes.nets import *

net = PetriNet('N')
netTree = net.__pnmldump__()
netTreeStr = repr(netTree) # I Send this to another program
print("net Type:", type(netTree))

net1 = PetriNet.__pnmlload__(net.__pnmldump__()) # Works
print("net1 PNML",repr(netTree))

# I Get the PNMLNetTreeStr on the other python program.
# I try to change type Str to PNMLTree
netTreeStr = Tree.from_pnml(netTreeStr)
print("netTree Type:", type(netTreeStr))
print("net3 PNML",repr(netTreeStr))
# Cannot Load PNMLnet
net2= PetriNet.__pnmlload__(netTreeStr) # Does not work
```
### Error
```
Traceback (most recent call last):
  File "test-snakes/pnmlImport.py", line 23, in <module>
    net2= PetriNet.__pnmlload__(netTreeStr) # Does not work
  File "snakes/nets.py", line 3271, in __pnmlload__
    result = cls(tree["id"])
  File "snakes/pnml.py", line 507, in __getitem__
    return self.attributes[name]
KeyError: 'id'
```
### Any Help is appreciated.
I am not a python Expert yet.
  - Tree, ClassMethods with id=self.name ? How does it actually work?

**Comment by himito** [comment]
Hi,

Perhaps this code helps you :)

```python
from snakes.nets import *
from snakes import pnml

net = PetriNet('N')
netTree = pnml.dumps(net)
print(netTree)  # Your Petri net

net2 = pnml.loads(netTree)
print(net2)

net3 = Tree.from_pnml(netTree)
print(net3)
```

**Comment by pksec** [comment]
@himito : Thanks, it worked! 

Closing the issue!

**Comment by fpom** [comment]
Thanks @himito, you're always so fast to answer!  :)
Indeed, methods __pnml*__ are not supposed to be called directly. There's additional machinery performed by module pnml.
