### ISSUE TITLE
Inhibitor arc guidance + runtime error

### ISSUE THREAD

**Issue by odanoburu** [fpom/snakes#26]
Hi,

I'm trying to familiarize myself with the library by implementing a toy petri net. I came up with the following:

``` python
from snakes.nets import *
import snakes.plugins
snakes.plugins.load('gv', 'snakes.nets', 'nets')
from nets import *

prod = PetriNet('Prod')

# places
prod.add_place(Place('p1', [1]))
prod.add_place(Place('p2'))
prod.add_place(Place('p3'))
prod.add_place(Place('p4'))
#prod.add_place(Place('sink'))

# t1
prod.add_transition(Transition('t1'))
prod.add_input('p1', 't1', Value(1))
prod.add_output('p1', 't1', Value(1))
prod.add_output('p3', 't1', Value(1))

# t2
prod.add_transition(Transition('t2'))
prod.add_input('p1', 't2', Value(1))
prod.add_output('p2', 't2', Value(1))

# t3
prod.add_transition(Transition('t3'))
prod.add_input('p2', 't3', Value(1))
# this throws an error:
#prod.add_input('p4', 't3', Inhibitor(Variable('y')))
prod.add_output('p1', 't3', Value(1))

# t4
prod.add_transition(Transition('t4'))
prod.add_input('p2', 't4', Value(1))
prod.add_input('p3', 't4', MultiArc([Value(1), Value(1), Value(1)]))
prod.add_input('p4', 't4', Inhibitor(Variable('x')))
prod.add_output('p2', 't4', Value(1))
prod.add_output('p4', 't4', Value(1))
```

To test it I run these transitions in the following order:

```python
def step():
    prod.transition('t1').fire(Substitution())
    prod.transition('t1').fire(Substitution())
    prod.transition('t1').fire(Substitution())
    print("After thrice t1:", prod.get_marking())

    prod.transition('t2').fire(Substitution())
    print("After t2:", prod.get_marking())

    # show possible substitutions enabling the transition
    print("Transition", prod.transition('t4').modes())
    # choose the substitution we will use to enable the transition
    ## NOTE: in this case there's only one option of substitution, but
    ## we may want to choose when there are several
    prod.transition('t4').fire(Substitution(x=0))
    print("After t4:", prod.get_marking())

    prod.transition('t3').fire(Substitution())
    print("After t3:", prod.get_marking())
```

My first Inhibitor arc problem is that from what I understand I shouldn't be able to run the step function twice, but I can. The `Inhibitor(Variable('x'))` in the input arc from `p4` to `t4` is supposed to prevent it from firing since `p4` is not empty.

The second problem arises when I uncomment the other instance of Inhibitor arc, and try to run step twice again. It shouldn't work indeed since the inhibitor arc should inhibit `t3` on the second step, but the error I get is:

```
Traceback (most recent call last):
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/data.py", line 831, in __getitem__
    return self._dict[var]
KeyError: 'y'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odanoburu/sites/petri-on-petri/prod.py", line 71, in <module>
    step()
  File "/home/odanoburu/sites/petri-on-petri/prod.py", line 65, in step
    prod.transition('t3').fire(Substitution())
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/nets.py", line 2680, in fire
    if self.enabled(binding) :
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/nets.py", line 2511, in enabled
    return self._check(binding, True, True)
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/nets.py", line 2460, in _check
    if not label.check(binding, place.tokens) :
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/nets.py", line 1732, in check
    return (not self._annotation.check(binding, tokens)
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/nets.py", line 470, in check
    return self.flow(binding) <= tokens
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/nets.py", line 482, in flow
    return MultiSet(v.value for v in iterate(self.bind(binding)))
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/nets.py", line 790, in bind
    return Token(binding[self.name])
  File "/home/odanoburu/sites/petri-on-petri/.venv/lib64/python3.10/site-packages/snakes/data.py", line 833, in __getitem__
    raise DomainError("unbound variable '%s'" % var)
snakes.DomainError: unbound variable 'y'
```

Am I doing something wrong? Did I misunderstand something? Thank you for any help!

**Comment by fpom** [comment]
Hi,
There was a bug, and I think it's now fixed. Inhibitor arcs are a recent addition that is not well tested nor well documented. Actually, you should not have to give a value for `x` when firing `t4` because firing is possible if there is no such `x`. In fact, `fire()` should be passed one of the modes returned by `mode()`. The fact that you gave `x` allowed the firing of `t4` without triggering the bug. But then, when adding the inhibitor arc with `y`, you did not provide `y` in the mode which triggered the bug. Now your example works with the empty modes as returned by `modes()`.

**Comment by odanoburu** [comment]
thank you very much! it works now :)
